### ISSUE TITLE
Creating database models for campus recruitment system

### ISSUE THREAD

**Issue by Riya-Singhal15** [einn-software/Campus_Recruitment_App#19]
As a developer, need to create all database models so that database operation can be performed. Following database models will be covered in this ticket - 
1. Registration Model
2. Instruction Model
3. Result Model
4. Question Paper Model
5. Questin Collections Model
Definition of done - 
Database operations / CRUD operations should be working with a automated test script.

**Comment by shikhagupta2611** [comment]
created all the models that are required for campus recruitment system.
commit id: 54df999
