### ISSUE TITLE
React work progress

### ISSUE THREAD

**Issue by atmanandsah** [einn-software/Campus_Recruitment_App#20]
Definition of done- implementation of the the following web user interface slides 
* Creating application directory structure in nodejs

***home page*** 2-3 days
   - [ ] HTML
   - [ ] HTML/CSS pages on server side
   - [ ] Navbar 
   - [ ] Footer

***login page***  2-3 days
 - [ ] Student Login 01-04-2020 till 5 pm
 - [ ] Admin Login
 - [ ]  College Login
 - [ ]  TPO Login

***Register page*** 2-3 days
- [ ] Student Registration
- [ ] Admin Registration
- [ ] College Registration
- [ ] TPO Registration

***Instruction page*** 2-hrs
- [ ] Instruction page of every new test

***Question page*** 2-3 days
- [ ] Question paper contains section and the section contains question and marks

***Result Page*** 1 days
- [ ] students marks scored 

***Selection of question from question bank for the new test*** 2-3 days
- [ ] web admin ui for making question paper

**Comment by atmanandsah** [comment]
working on functional components like clicking buttons events

**Comment by kanchan-einn** [comment]
Definition of done - 
All user interfaces should be completed and working.

Sub tasks -

**Comment by atmanandsah** [comment]
Definition of done - 
adding components such as Navbar and einn logo , registration components and login components

Sub tasks-
adding components #27

**Comment by atmanandsah** [comment]
Definition of done-
registration routes such as admin registration student registration and college registration

Sub tasks-
registration routes #30
date of done - 04-04-2020

**Comment by atmanandsah** [comment]
Definition of done-
login routes such as students login, admin login , college login

Sub tasks-
login routes #29
date of done-
05/04/2020

**Comment by atmanandsah** [comment]
Definition of done-
instruction page,question page,result page

Sub tasks-
Test WebPage #32
date of done-
10-04-2020

**Comment by atmanandsah** [comment]
Definition of done-
selecting the question for different section

Sub tasks-
Making the question paper for the different college from the question database #33
date of done -
18-04-2020
