### ISSUE TITLE
Planning to implement backend for Campus_Recruitment_System

### ISSUE THREAD

**Issue by shikhagupta2611** [einn-software/Campus_Recruitment_App#35]
**Assigned to Shikha**
**1) To Create Database models for the following:**                                            (#19 All Created)
        a)Registration Model                                                                              
              i)Admin
              ii)College
              iii)TPO
              iv)Student              
        b)Instructions Model
        c)Question Collections Models
        d)Question Papers Models
        e)Results Model

**2) Model Unit Test cases - (5-6 days)**
          * Instructions model Test cases (#41  created and committed)
          * Result model Test Cases (#45  created and committed)
          * Register model Test cases  (#45  created and committed)
          * Question Collection model Test Cases  (#47 created and committed)
          * Question Paper model Test cases  (#51 created and commited)
          
         
__________________________________________________________________________________________________________

**Assigned to Riya  --**
**1) To Create API for the following -**                                                                 
        a) **Registration API**                          (#25 All Created and committed -- commit no- 7eeeb02cd291cf562ab1b2c4c35545e80a3effbf)
               * Admin Register API
               * College Register API
               * TPO Register API
               * Student Register API
 b) **Login API**                                           (#25 All Created and committed -- commit no- 7eeeb02cd291cf562ab1b2c4c35545e80a3effbf)
               * Admin login API
               * College login API
               * TPO login API
               * Student login API
        c) Instruction API   (#28 Created, commit no- 6aeee9c78171dbe4d09aca9ef052045f56839d6e)                                                           
         d) Question collection and question paper API  (#53 Created and committed, commit no- 1524003745d445c7a9f098c69c37f22bb52b1e0a)                                                                                                                  
         e) Result API  (#28 Created, commit no- 6aeee9c78171dbe4d09aca9ef052045f56839d6e)                                                                          

**2) API Unit Test cases - Positive and negative both - (4-5 days)**
          * **Register API Test cases** for Tpo register, College register, Admin register, and Student 
               register (#37 all created commit no. ce4ebcaf8f004255f807e86a2066dde013011bd6)
          * Login API Test cases  (#50 created and commited, commit no- 74853adc1c29f7c3ef5343659f9ed4e3f6d8e719)
          * Instruction API Test cases (#48 created and commit no- dbefaf2b6277c73071f7d841966dc8f1c838ee1c)
          * Question Collection and Question paper API Test cases (#53 created but having some error)
          * Result API Test Cases (#48 created and commit no- dbefaf2b6277c73071f7d841966dc8f1c838ee1c)
  
There is a gap in the documentation, some HTTP methods are missing in the API Doc, so we have to implement that first. Those are the DELETE and PUT requests in each API and their test cases. 
* Delete and Put methods of All the APIs (created and committed, commit-id: fc69af1)

* And their test cases are created.

* Our latest task is to work on the server and commit our node application on the server.
**Total backend project will be completed by 15 of April in proper working condition.**

**Comment by Riya-Singhal15** [comment]
All the APIs are completed and committed inside the branch Task/CRA-80.
