### ISSUE TITLE
Preparing a presentation for the front-end layouts

### ISSUE THREAD

**Issue by Riya-Singhal15** [einn-software/Campus_Recruitment_App#54]

**Comment by Riya-Singhal15** [comment]
[Campus recruitment website screens (1).pptx](https://github.com/einn-software/Campus_Recruitment_App/files/4486436/Campus.recruitment.website.screens.1.pptx)

**Comment by Riya-Singhal15** [comment]
[website screens.pptx](https://github.com/einn-software/Campus_Recruitment_App/files/4492476/website.screens.pptx)

**Comment by kanchan-einn** [comment]
Slides are finalised, hence closing.
