### ISSUE TITLE
Creating Login Page

### ISSUE THREAD

**Issue by shikhagupta2611** [einn-software/Campus_Recruitment_App#58]
### Login page to be implemented are -
   Admin Login Page
   Student Login Page
   Tpo Login Page
   College Login Page

**Comment by Riya-Singhal15** [comment]
Admin Login Page created and committed. (Commit no- 88af4c08e8dc39ced66c0405a662d821e2464ac6)

**Comment by shikhagupta2611** [comment]
All pages created and commited commit no-  702626d9990f4554f2dfb0a5ce55050285833765
