### ISSUE TITLE
Implementation of Dashboard Pages for campus recruitment project

### ISSUE THREAD

**Issue by shikhagupta2611** [einn-software/Campus_Recruitment_App#61]
### The Dashboard Pages mentioned below are to be implemented for the Campus recruitment project -

1. Admin Dashboard Page (created)

1. CollegeDashboard Page (will be created by 01-05-2020)

1. StudentDashboard Page

**Comment by Riya-Singhal15** [comment]
Admin Dashboard is created and committed (commit no.- 780f31a3729c19ecd384886ee65686d44c214962)
