### ISSUE TITLE
Learning concepts of the android

### ISSUE THREAD

**Issue by shubham0520** [einn-software/Campus_Recruitment_App#64]
in this section i will learn the concept of the android and other necessary concept which will be required

**Comment by shubham0520** [comment]
completed layout revision and data binding libraries in the android

**Comment by shubham0520** [comment]
today completed data binding with the power point presentation

**Comment by nidhi-einn** [comment]
@shubham0520 I need day wise plan for work in this week.

**Comment by shubham0520** [comment]
- 18 may- activity and fragment life cycle

- 19 may- app architecture(UI layer)

- 20 may- app architecture(persistence) means database and server

- 21 may- recycler view and and other views

- 22 may- connect to internet

**Comment by shubham0520** [comment]
All the mentioned topics has been covered theoretically but not made the ppt of that because of laptop failure.

**Comment by nidhi-einn** [comment]
Shubham will present this topics when his laptop will work.
