### ISSUE TITLE
Testing all the Retrofit Requests for data assertion.

### ISSUE THREAD

**Issue by shresthdeepgupta** [einn-software/Campus_Recruitment_App#66]
we have to check all the incoming responses from API to check whether the responses are as described in the API Docs and whether the outgoing requests are correct or not...
The  four repositories handling the requests are:

- UserRemoteRepository
- ExaminationRemoteRepository
- InstructionRemoteRepository
- ResultRemoteRepository
  changed date

**Comment by shresthdeepgupta** [comment]
I'll be Handling testing of two repositories namely:

- **UserRemoteRepository**
- **ExaminationRemoteRepository**

@akanksha-einn  will work on : 
 - **InstructionRemoteRepository**
 - **ResultRemoteRepository**

**Comment by shresthdeepgupta** [comment]
Completed writing my unit tests for concern repositories, found some errors that are needed to be rectified in the API, will open a ticket for the same listing all the required changes

**Comment by nidhi-einn** [comment]
@shresthdeepgupta and @akanksha-einn  this ticket is only for Shresth. Please create separate ticket for your work. So Instruction and Result module will not cover as part of this ticket.

**Comment by nidhi-einn** [comment]
@shresthdeepgupta please mention on which module Api are you working?

**Comment by shresthdeepgupta** [comment]
currently working on ExaminationRemoteRepository

**Comment by shresthdeepgupta** [comment]
Access Denied from Question paper , questions , answersheet APIs
