### ISSUE TITLE
Changes to be made in API responses

### ISSUE THREAD

**Issue by shresthdeepgupta** [einn-software/Campus_Recruitment_App#67]
The API responses are not complying with the requirement, they need to be corrected. further, some requests are not working correctly, will inform about them afterward.

Changes to be made :

  - Error Response should be provided in JSON 
 
  - [x] other than this,  Dummy data should be present in each table for testing

**Comment by akanksha-einn** [comment]
I am getting "HTTP 400 Bad Request" in response of getResult(token, rollNo) Api call

**Comment by Riya-Singhal15** [comment]
Dummy Data is added, all the response are in json format now.
