### ISSUE TITLE
Updating API Docs

### ISSUE THREAD

**Issue by shresthdeepgupta** [einn-software/Campus_Recruitment_App#68]
There have been many changes in the API as per requirement but none of them is reflected in API Docs which is creating confusion regarding API to Reader, please update API Doc as soon as any changes occur in the API.

for example, there been changes in API  in **Instruction model** but is not updated in the API Docs

This is not in only API Docs but in the wiki itself, whoever has made some changes during the project must update the wiki docs, so that everyone else could be up to date, that's why I'm assigning this ticket to all working on the project

**Comment by Riya-Singhal15** [comment]
All the changes are updated inside the updated API docs.
