### ISSUE TITLE
Test Instruction call Api

### ISSUE THREAD

**Issue by akanksha-einn** [einn-software/Campus_Recruitment_App#71]
we have to check all the incoming responses from API to check whether the responses are as described in the API Docs and whether the outgoing requests are correct or not for Instruction Api.

DoD:
1.  Change the following according to new API doc:
     1.1. Network Repository 
     1.2.  UI
     1.3. Models
     1.4. Interactor
2. Unit test functions for Get Instruction api

Eastimated time: 1 Day

**Comment by nidhi-einn** [comment]
@akanksha-einn please complete this ticket work and submit your code for review.
