### ISSUE TITLE
Test Result Api

### ISSUE THREAD

**Issue by akanksha-einn** [einn-software/Campus_Recruitment_App#74]
we have to check all the incoming responses from API to check whether the responses are as described in the API Docs and whether the outgoing requests are correct or not for Result Api.

DOD:-
1. Change ResultRepo according to new Api doc
2. Change in retrofit for result according to new Api doc
3. Implement Unit test Cases for Result Api

Eastmated time: 2 Day

**Comment by nidhi-einn** [comment]
@akanksha-einn please update this ticket.
