### ISSUE TITLE
List all Controller classes and divide them between Shubham and Shresth to track the progress.

### ISSUE THREAD

**Issue by kanchan-einn** [einn-software/Campus_Recruitment_App#8]

**Comment by shresthdeepgupta** [comment]
I have done implementing Login Activity and done some work on Register Activity..

**Comment by shresthdeepgupta** [comment]
list of controllers I'll be developing:

1. LoginCategoryPresenter
2. AdminLoginPresenter
3. AdminRegisterPresenter
4. AdminDashboardPresenter
5. Student RegisterPresenter
6. CollegeRegisterPresenter
7. QuestionUploadPresenter

**Comment by shubham0520** [comment]
there is some unnecessary presenter you have committed these would be made by atmanand and team

**Comment by shubham0520** [comment]
list of controllers I'll be developing:-
>1. IntructionPagePresenter
>2. ExamWindowPresenter
>3. ResultWindowPresenter
>4. studentLoginPresenter
>5. nevigationPresenter
